# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # See: https://github.com/ImperialCollegeLondon/FROG/issues/739
      - dependency-name: python-statemachine
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
