name: Set up
description: Set up Python environment and install dependencies
inputs:
  python-version:
    description: The Python version to use
    required: true

runs:
  using: "composite"
  steps:
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        activate-environment: true
        python-version: ${{ inputs.python-version }}

    - name: Install project
      shell: bash
      run: uv sync --all-groups

    - name: Install system dependencies in Linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt update

        # Without this, PySide6 gives an ImportError
        sudo apt install libegl1
