name: Build documentation
description: Build documentation with MkDocs

runs:
  using: "composite"
  steps:
    - name: Install dot for generating diagrams
      if: runner.os == 'Linux'
      shell: bash
      run: sudo apt install graphviz

    - name: Build documentation with MkDocs
      shell: bash
      run: |
        uv run docs/gen_state_machine_diagrams.py
        uv run mkdocs build --strict
