name: Set up Python environment and install dependencies
on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  setup:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Install Poetry
        run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: poetry

      - name: Install system dependencies in Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt update

          # For documentation
          sudo apt install graphviz

          # Without this, PySide6 gives an ImportError
          sudo apt install libegl1

      - name: Install dependencies
        run: |
          poetry env use "${{ inputs.python-version }}"
          poetry install
